### ISSUE TITLE
Is there a way to get post slug or path from inside blog_post_base.blade.php file?

### ISSUE THREAD

**Issue by mabasic** [themsaid/katana#10]
Something like:

```
{{ $post->slug }}

or

{{ $post->path }}
```

I have seen `blogPosts` variable, but that contains all posts. I want just the current post data.

**Comment by themsaid** [comment]
Just released a new version `https://github.com/themsaid/katana-core/releases/tag/v1.1.0`.

In this version I added `$currentViewPath` and `$currentUrlPath` to all views, you may use them to get the path of the view from the filesystem and the current URL.

**Comment by mabasic** [comment]
Thank you very much. This helped me a lot.
