### ISSUE TITLE
Blog URLs without dates

### ISSUE THREAD

**Issue by dailysleaze** [themsaid/katana#12]
I'm thinking of migrating my wordpress site to Katana as it's pretty much what i'm looking for. 

My current URL structure is /category/slug. It would be good to not require a date in the URL, as at the moment all URLs without dates go to `-/`.

Is there some way to create a URL hierachy with the blogs? I tried a sub-directory inside _blog, but goes into the public folder as `_blog/folder/file`.

I realise that the pages can do this, but having an array with all of the blogs in is useful. An alternative could be to have an array of all of the pages? This would allow you to print all pages easily.

Thanks!

**Comment by themsaid** [comment]
Hello there,

Thank you for the suggestion, it's a good one as it allows categorising blog posts and gives more flexibility to the whole blog generator.

I've released [v1.2.0](https://github.com/themsaid/katana-core/releases/tag/v1.2.0) of the core repository that includes the ability to use nested directories inside the blog generator. So now you can do:

```
/_blog/2016-03-24-my-post.md
/_blog/php/my-php-post.md
/_blog/javascript/my-js-post.md
```

Doing so will give you the ability to generate better URL's and the posts will be available in the `$blogPosts` variable on every view.

Please give it a shot and let me know your feedback.

**Comment by dailysleaze** [comment]
Thanks for responding to my idea. Sorry for the delay i've been away.

Unfortunately I couldn't get it to work with a fresh install. By creating a directory in the `_blog` directory, all URLs would still be set as `-`. I'm not sure if I'm doing something wrong?!? Some screenshots

Hovering on the link
![image1](https://cloud.githubusercontent.com/assets/3210226/14226524/eb73442c-f8dc-11e5-9995-c5254834e46f.gif)

Folder structure
![image2](https://cloud.githubusercontent.com/assets/3210226/14226525/eb750406-f8dc-11e5-80ce-b012599789e6.gif)

Blog file contents
![image3](https://cloud.githubusercontent.com/assets/3210226/14226526/eb7734ce-f8dc-11e5-900b-aa8004be0cee.gif)

**Comment by dailysleaze** [comment]
I think this pattern isn't matching `*/_blog/*/*` @ https://github.com/themsaid/katana-core/commit/401cc1a8629239ae87dfabd2d31465640bfdffc8#diff-d1fded158e38ae22361fb06ff5210cfbR57

If I comment this out, the URLs are created with the correct structure, but are shown as absolute instead of relative, e.g. `http://php/my-php-post` instead of `http://site.com/php/my-php-post`
