### ISSUE TITLE
[feature] Config option for blog URI

### ISSUE THREAD

**Issue by Omranic** [themsaid/katana#13]
It would be nice if there is a config option to set custom blog URI rather than the hard coded 'blog' used in all blog links..

**Comment by themsaid** [comment]
You can host the blog anywhere you want, just change the `blog` view bane and update the cofnigs file for key `postsListView`

**Comment by Omranic** [comment]
What about the hardcoded pagination links `vendor/themsaid/katana-core/src/BlogPaginationBuilder.php`?

**Comment by themsaid** [comment]
It's just a prefix `blog-page`, if you think customising it is useful I'd be glad to merge a PR on that :) Just try to make it backward compatible by providing a default value `blog-page` in case of the absence of the new config key you'll be adding.

**Comment by Omranic** [comment]
Cool, I'll send it this week.. Keep up the good work..

**Comment by Omranic** [comment]
I'll close this for now as I'll rethink this feature and others..
