### ISSUE TITLE
Posts are not sorted by date

### ISSUE THREAD

**Issue by yskoverride** [themsaid/katana#21]
The /blog page does not sorts blog posts based on dates. Does it sorts by last edited time of a blog post.

**Comment by vidalvasconcelos** [comment]
@yskoverride in the sidebar "From blog"?

**Comment by yskoverride** [comment]
@vidalvasconcelos the problem is with the blog posts page, not the sidebar. I am manually changing the positions of the posts in /blog/ page as a workaround.
