### ISSUE TITLE
Markdown from file

### ISSUE THREAD

**Issue by franzliedke** [themsaid/katana#5]
As mentioned on [Laravel News](https://laravel-news.com/2016/03/katana-blade-powered-static-site-blog-generator/), Markdown syntax highlighting will probably break when using it with the `@markdown` directive.

Could you add another alternative, that instead loads the post content from a file?

Great project, by the way. :)

**Comment by themsaid** [comment]
Thank you for your feedback :)

I use [MacDown](http://macdown.uranusjr.com/) and things seem to work so far, however of course a natural `.md` file would work better.

I'm thinking of rendering `.md` files by injecting its content in a base `.blade` view and compile  `@bladeDirectives` inside the `.md` file after injection.

What do you think?

**Comment by franzliedke** [comment]
Hmm, I don't know. I think I still prefer the pure Markdown files.

What kind of directive would be used in a MD file? (That said, shouldn't we get this for free by simply including `.blade.md` files?)

**Comment by themsaid** [comment]
The idea is to introduce the possibility of using `.blade.php` and `.md` files both. In case you choose to have a `.md` file you'll need to choose the base blade view where the post content will be injected.

**Comment by themsaid** [comment]
You can now use `.md` files to generate your pages & blog posts: http://themsaid.github.io/katana/#markdown-files

You'll still be able to use Blade directives inside your markdown files, that way you'll have pure markdown files with the flexibility of blade.
