### ISSUE TITLE
Support environment-based parameter value

### ISSUE THREAD

**Issue by rokde** [themsaid/katana#6]
Can you integrate an environment based parameter value?

For example google analytics id for production environment should differ from local or test environment.

**Comment by themsaid** [comment]
That seems like a very useful feature, thank you for the suggestion, I think I'll look into that very soon.

**Comment by themsaid** [comment]
This is now available in v1.0.0 via:

```
php katana build --env=production
```

You may create a `config-production.php` file with configurations that'll overwrite the ones in `config.php`.
